### ISSUE TITLE
RelPos() fails when shape is not 'rectangle' and stand is specified 

### ISSUE THREAD

**Issue by benjaminmisiuk** [ailich/MultiscaleDTM#64]
If `shape = 'circle'` or `'annulus'` and `stand = 'sd'` or `'range'`, `RelPos()` produces an error. I think it's because stand works "by dividing by the standard deviation or range of included values in the focal window", yet with circular or annulus shapes we have no `w`.

```
r <- rast(volcano, extent= ext(2667400, 2667400 + ncol(volcano)*10, 6478700, 6478700 + nrow(volcano)*10), crs = "EPSG:27200")
rp <- RelPos(r, radius = 3, shape = 'circle', stand = 'sd')

#Error in .local(x, ...) : all(w > 0) is not TRUE
```

**Comment by ailich** [comment]
Thanks @benjaminmisiuk! The source of that is because I apparently because [I forgot to switch the call from `w` to `w_mat` ](https://github.com/ailich/MultiscaleDTM/blob/44c1092d73eda626b31bb43355e2ceff151e2b4a/R/RelPos.R#L238-L243)in `focal` since internally `RelPos` takes the various inputs to build a focal weights matrix,
